=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixMtmApi::CustomFeaturesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomFeaturesApi' do
  before do
    # run before each test
    @api_instance = LeanixMtmApi::CustomFeaturesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomFeaturesApi' do
    it 'should create an instance of CustomFeaturesApi' do
      expect(@api_instance).to be_instance_of(LeanixMtmApi::CustomFeaturesApi)
    end
  end

  # unit tests for create_custom_feature
  # createCustomFeature
  # Endpoint to set a customFeature. Restricted to LeanIX internal use only.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CustomFeatureResponse]
  describe 'create_custom_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_custom_feature
  # deleteCustomFeature
  # Endpoint to delete a custom feature. Restricted to LeanIX internal use only.
  # @param id CustomFeature UUID
  # @param [Hash] opts the optional parameters
  # @return [CustomFeatureResponse]
  describe 'delete_custom_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_feature
  # getCustomFeature
  # Endpoint to get a custom feature. Restricted to LeanIX internal use only.
  # @param id CustomFeature UUID
  # @param [Hash] opts the optional parameters
  # @return [CustomFeatureResponse]
  describe 'get_custom_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_features
  # getCustomFeatures
  # Retrieves settings. Restricted to LeanIX internal use only.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :contract_id Contract UUID
  # @option opts [String] :workspace_id Workspace UUID
  # @return [CustomFeatureListResponse]
  describe 'get_custom_features test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_custom_feature
  # updateCustomFeature
  # Endpoint to update a custom feature. Restricted to LeanIX internal use only.
  # @param id CustomFeature UUID
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CustomFeatureResponse]
  describe 'update_custom_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
