=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixMtmApi::DomainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DomainsApi' do
  before do
    # run before each test
    @api_instance = LeanixMtmApi::DomainsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainsApi' do
    it 'should create an instance of DomainsApi' do
      expect(@api_instance).to be_instance_of(LeanixMtmApi::DomainsApi)
    end
  end

  # unit tests for delete_domain
  # deleteDomain
  # Deletes a domain and the respective CNAME. Restricted to LeanIX internal use only.
  # @param fqdn Customer fqdn
  # @param [Hash] opts the optional parameters
  # @return [IdentityProviderResponse]
  describe 'delete_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domain
  # getDomain
  # Retrieves a specific domain. Restricted to LeanIX internal use only.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domains
  # getDomains
  # Retrieves all domains. Restricted to LeanIX internal use only.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :q A part of the FQDN to search for
  # @option opts [String] :fqdn FQDN of the IDP (is unique over all domains)
  # @option opts [String] :instance Current workspace&#39;s instance ID
  # @option opts [Integer] :page The page number to access (1 indexed, defaults to 1)
  # @option opts [Integer] :size The page size requested (defaults to 30, max 100)
  # @option opts [String] :sort Comma-separated list of sorting (optional)
  # @return [DomainListResponse]
  describe 'get_domains test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_workspaces
  # getWorkspaces
  # Retrieves all workspaces for a domain. Restricted to LeanIX internal use only.
  # @param id Domain UUID
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceListResponse]
  describe 'get_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_domain
  # upsertDomain
  # Creates or updates a domain and the respective CNAME. Restricted to LeanIX internal use only.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [DomainResponse]
  describe 'upsert_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
