=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixMtmApi::IdmApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IdmApi' do
  before do
    # run before each test
    @api_instance = LeanixMtmApi::IdmApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdmApi' do
    it 'should create an instance of IdmApi' do
      expect(@api_instance).to be_instance_of(LeanixMtmApi::IdmApi)
    end
  end

  # unit tests for activate
  # activate
  # User self activation
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'activate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for authenticate
  # authenticate
  # Endpoint to check user credentials (netId + password) for system users. Restricted to LeanIX internal use only.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'authenticate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_ip
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'check_ip test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for invite
  # invite
  # Invite a user to a workspace
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :silent Enables silent mode. No emails are sent out then. (optional)
  # @return [UserResponse]
  describe 'invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login
  # login
  # Notifies MTM of a login at a remote workspace. Can be called by systems only. Restricted to LeanIX internal use only.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [LoginResponse]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_practitioner
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'login_practitioner test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for logout
  # logout
  # Notifies MTM of a logout at a remote workspace. Invalidates the access token used for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [BasicResponse]
  describe 'logout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_password
  # resetPassword
  # Endpoint to start the reset the password process, can only be accessed by systems.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CredentialsResponse]
  describe 'reset_password test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for review
  # review
  # Confirm or deny an invitation
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [PermissionListResponse]
  describe 'review test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_new_password
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set_new_password test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_password
  # setPassword
  # Endpoint to finish the reset the password process.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UserResponse]
  describe 'set_password test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for switch_permission_role
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'switch_permission_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
