=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixMtmApi::InactiveApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InactiveApi' do
  before do
    # run before each test
    @api_instance = LeanixMtmApi::InactiveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InactiveApi' do
    it 'should create an instance of InactiveApi' do
      expect(@api_instance).to be_instance_of(LeanixMtmApi::InactiveApi)
    end
  end

  # unit tests for get_inactive_users
  # inactive
  # List inactive users. Restricted to LeanIX internal use only.
  # @param workspace_id The id of the workspace to query for inactive users.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :alpha The alpha value for significance, when classifying users as inactive.
  # @option opts [Integer] :min_days_until_absent Minimum amount of days, when a regular user is seen as inactive regardless of usual login behavior.
  # @return [UserListResponse]
  describe 'get_inactive_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
