=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixMtmApi::JobTitleDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixMtmApi::JobTitleDTO do
  let(:instance) { LeanixMtmApi::JobTitleDTO.new }

  describe 'test an instance of JobTitleDTO' do
    it 'should create an instance of JobTitleDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixMtmApi::JobTitleDTO)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ENTERPRISE_ARCHITECT", "SOLUTION_ARCHITECT", "APPLICATION_OWNER", "IT_MANAGEMENT", "PROJECT_MANAGER", "SECURITY_MANAGER", "BUSINESS_ANALYST", "SW_ENGINEER", "OTHER_BUSINESS", "OTHER_IT", "DECLINED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.key = value }.not_to raise_error
      # end
    end
  end

end
