=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixMtmApi::JobToBeDoneDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixMtmApi::JobToBeDoneDTO do
  let(:instance) { LeanixMtmApi::JobToBeDoneDTO.new }

  describe 'test an instance of JobToBeDoneDTO' do
    it 'should create an instance of JobToBeDoneDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixMtmApi::JobToBeDoneDTO)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["EA_CORE_JOB", "ANALYSE_ARCHITECTURE", "PLAN_ARCHITECTURE", "CREATE_AND_SHARE_VISUALIZATIONS", "UPDATE_INFORMATION", "VIEW_IT_KPIS", "GENERATE_INSIGHTS", "PLAN_AND_TRACK_PROJECTS", "CHECK_IT_COMPLIANCE", "VIEW_ROADMAPS", "UNDERSTAND_BCS", "VIEW_USED_TECH", "VIEW_RECOMMENDED_TECH", "FIND_COLLEAGUE", "ANALYSE_ITSUPPORT_FOR_BUSINESS", "OTHER", "DECLINED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.key = value }.not_to raise_error
      # end
    end
  end

end
