=begin
#MTM

#Multi-tenancy-manager for LeanIX. Manages accounts, contracts, users, workspaces, permissions, and more.

The version of the OpenAPI document: 1.6.348

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module LeanixMtmApi
  class Workspace
    attr_accessor :id

    attr_accessor :contract

    attr_accessor :instance

    attr_accessor :domain

    attr_accessor :name

    attr_accessor :feature_bundle_id

    attr_accessor :status

    attr_accessor :type

    attr_accessor :product

    attr_accessor :default_role

    attr_accessor :comment

    attr_accessor :created_at

    attr_accessor :invitation_only

    attr_accessor :allow_transient_users

    attr_accessor :replayed

    attr_accessor :replayed_v2

    attr_accessor :url

    attr_accessor :active

    attr_accessor :created_from_template

    attr_accessor :links

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'contract' => :'contract',
        :'instance' => :'instance',
        :'domain' => :'domain',
        :'name' => :'name',
        :'feature_bundle_id' => :'featureBundleId',
        :'status' => :'status',
        :'type' => :'type',
        :'product' => :'product',
        :'default_role' => :'defaultRole',
        :'comment' => :'comment',
        :'created_at' => :'createdAt',
        :'invitation_only' => :'invitationOnly',
        :'allow_transient_users' => :'allowTransientUsers',
        :'replayed' => :'replayed',
        :'replayed_v2' => :'replayedV2',
        :'url' => :'url',
        :'active' => :'active',
        :'created_from_template' => :'createdFromTemplate',
        :'links' => :'links'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'contract' => :'Contract',
        :'instance' => :'Instance',
        :'domain' => :'Domain',
        :'name' => :'String',
        :'feature_bundle_id' => :'String',
        :'status' => :'String',
        :'type' => :'String',
        :'product' => :'String',
        :'default_role' => :'String',
        :'comment' => :'String',
        :'created_at' => :'Time',
        :'invitation_only' => :'Boolean',
        :'allow_transient_users' => :'Boolean',
        :'replayed' => :'Boolean',
        :'replayed_v2' => :'Boolean',
        :'url' => :'String',
        :'active' => :'Boolean',
        :'created_from_template' => :'Boolean',
        :'links' => :'Array<Link>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LeanixMtmApi::Workspace` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LeanixMtmApi::Workspace`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'contract')
        self.contract = attributes[:'contract']
      else
        self.contract = nil
      end

      if attributes.key?(:'instance')
        self.instance = attributes[:'instance']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'feature_bundle_id')
        self.feature_bundle_id = attributes[:'feature_bundle_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'product')
        self.product = attributes[:'product']
      end

      if attributes.key?(:'default_role')
        self.default_role = attributes[:'default_role']
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'invitation_only')
        self.invitation_only = attributes[:'invitation_only']
      end

      if attributes.key?(:'allow_transient_users')
        self.allow_transient_users = attributes[:'allow_transient_users']
      end

      if attributes.key?(:'replayed')
        self.replayed = attributes[:'replayed']
      end

      if attributes.key?(:'replayed_v2')
        self.replayed_v2 = attributes[:'replayed_v2']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end

      if attributes.key?(:'created_from_template')
        self.created_from_template = attributes[:'created_from_template']
      end

      if attributes.key?(:'links')
        if (value = attributes[:'links']).is_a?(Array)
          self.links = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @contract.nil?
        invalid_properties.push('invalid value for "contract", contract cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @contract.nil?
      status_validator = EnumAttributeValidator.new('String', ["ACTIVE", "BLOCKED"])
      return false unless status_validator.valid?(@status)
      type_validator = EnumAttributeValidator.new('String', ["LIVE", "DEMO", "SANDBOX"])
      return false unless type_validator.valid?(@type)
      product_validator = EnumAttributeValidator.new('String', ["EAM", "VSM", "SMP"])
      return false unless product_validator.valid?(@product)
      default_role_validator = EnumAttributeValidator.new('String', ["ADMIN", "MEMBER", "VIEWER", "CONTACT", "SYSTEM_READ", "SYSTEM_WRITE", "SYSTEM_AS_USER", "TRANSIENT"])
      return false unless default_role_validator.valid?(@default_role)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACTIVE", "BLOCKED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["LIVE", "DEMO", "SANDBOX"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] product Object to be assigned
    def product=(product)
      validator = EnumAttributeValidator.new('String', ["EAM", "VSM", "SMP"])
      unless validator.valid?(product)
        fail ArgumentError, "invalid value for \"product\", must be one of #{validator.allowable_values}."
      end
      @product = product
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] default_role Object to be assigned
    def default_role=(default_role)
      validator = EnumAttributeValidator.new('String', ["ADMIN", "MEMBER", "VIEWER", "CONTACT", "SYSTEM_READ", "SYSTEM_WRITE", "SYSTEM_AS_USER", "TRANSIENT"])
      unless validator.valid?(default_role)
        fail ArgumentError, "invalid value for \"default_role\", must be one of #{validator.allowable_values}."
      end
      @default_role = default_role
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          contract == o.contract &&
          instance == o.instance &&
          domain == o.domain &&
          name == o.name &&
          feature_bundle_id == o.feature_bundle_id &&
          status == o.status &&
          type == o.type &&
          product == o.product &&
          default_role == o.default_role &&
          comment == o.comment &&
          created_at == o.created_at &&
          invitation_only == o.invitation_only &&
          allow_transient_users == o.allow_transient_users &&
          replayed == o.replayed &&
          replayed_v2 == o.replayed_v2 &&
          url == o.url &&
          active == o.active &&
          created_from_template == o.created_from_template &&
          links == o.links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, contract, instance, domain, name, feature_bundle_id, status, type, product, default_role, comment, created_at, invitation_only, allow_transient_users, replayed, replayed_v2, url, active, created_from_template, links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = LeanixMtmApi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
